version: "3.8"

services:
  delivery-api:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      PORT: 3003
      DATABASE_URL: ${DATABASE_URL}
      ORDER_URL: ${ORDER_URL}
      NOTIFICATION_URL: ${NOTIFICATION_URL}
    networks:
      - shoong-network

networks:
  shoong-network:
    external: true